# docker compose config to run a development instance
# of the mediaserver tool

services:
  server:
    build: 
      dockerfile: Dockerfile.server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    working_dir: /app
    command: npm run dev
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      STAGE: ${STAGE}
      MIGRATIONS_DIR: assets/db/migrations
      DEFAULT_THUMBNAIL_PATH: assets/icons/unknown_file.jpg
      DOCUMENT_STORE_CONFIG_PATH: assets/documentStoreConfig.json
      IGNORE_MIGRATION_CHECKSUM_MISMATCHES: true
      MAX_FILE_UPLOAD_SIZE: 2147483648 # 2GB
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./server:/app:ro
      - ./data:/data
      - /home/lars/mediaserver/store:/store-0
      - /tmp:/tmp
      - server_dist:/app/dist
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}

  frontend:
    image: node:20
    depends_on:
      server:
        condition: service_healthy
    restart: always
    working_dir: /app
    command: npm run dev
    environment:
      VITE_BACKEND_URL: "http://192.168.0.44:${BACKEND_PORT}"
      VITE_WEBSOCKET_URL: "ws://192.168.0.44:${WEBSOCKET_PORT}"
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173

  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  server_dist:
  redis_data:
