on: 
  pull_request:
    branches:
      - main
      - develop
  merge_group:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    if: github.event_name != 'pull_request' || github.event.action == 'enqueued'
    name: Release

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine release type
        run: |
          if [[ "${{ github.event.merge_group.base_ref }}" == "main" ]]; then
            echo "RELEASE_TYPE=stable" >> $GITHUB_ENV
          else
            echo "RELEASE_TYPE=unstable" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/

      - uses: paulhatch/semantic-version@v5.4.0
        id: version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN  }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Server Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            treelabmediaserver/mediaserver-backend:${{ steps.version.outputs.version }}
            treelabmediaserver/mediaserver-backend:${{ env.RELEASE_TYPE }}
            ${{ env.RELEASE_TYPE == 'stable' && 'treelabmediaserver/mediaserver-backend:latest' || '' }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            treelabmediaserver/mediaserver-web:${{ steps.version.outputs.version }}
            treelabmediaserver/mediaserver-web:${{ env.RELEASE_TYPE }}
            ${{ env.RELEASE_TYPE == 'stable' && 'treelabmediaserver/mediaserver-web:latest' || '' }}

      - name: Publish frontend plugin types to NPM
        run: |
          cd frontend
          npm install
          cd ../plugin/frontend-types
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version
          npm install
          npm publish --provenance --ignore-scripts --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish backend plugin types to NPM
        run: |
          cd server
          npm install
          cd ../plugin/backend-types
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version
          npm install
          npm publish --provenance --ignore-scripts --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish plugin creation tool to NPM
        run: |
          cd plugin/create-plugin
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version
          npm install
          npm run build
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
